// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThinKsaDev.ItDeveloper.Data.Data.ORM;

#nullable disable

namespace ThinKsaDev.ItDeveloper.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThinKsaDev.ItDeveloper.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("Cpf")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Email");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("HospitalizationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Nome");

                    b.Property<Guid>("PatientStateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PatientType")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("varchar(90)");

                    b.Property<string>("Rg")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Rg");

                    b.HasKey("Id");

                    b.HasIndex("PatientStateId");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("ThinKsaDev.ItDeveloper.Domain.Entities.PatientState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("Varchar(30)")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.ToTable("PatientState", (string)null);
                });

            modelBuilder.Entity("ThinKsaDev.ItDeveloper.Domain.Entities.Patient", b =>
                {
                    b.HasOne("ThinKsaDev.ItDeveloper.Domain.Entities.PatientState", "PatientState")
                        .WithMany("Patients")
                        .HasForeignKey("PatientStateId")
                        .IsRequired();

                    b.Navigation("PatientState");
                });

            modelBuilder.Entity("ThinKsaDev.ItDeveloper.Domain.Entities.PatientState", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
